name: Action Test 2
description: Foo bar
runs:
  using: docker
  image: Dockerfile
inputs:
  args:
    description: Additional arguments to the sonarcloud scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
